spring:
  config:
    activate:
      on-profile: local
  devtools:
    livereload:
      enabled: true   # Live Reload
  datasource:
    url: jdbc:mysql://localhost:3306/kkamjidot_schema?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver   # MySQL 연결 설정
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate

server:
  port: 8080

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

springdoc:
  version: 'v1.0.0' # API 문서 버전
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    doc-expansion: list
    operations-sorter: alpha