spring:
  profiles:
    active: ${active}

# multipart settings
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 10MB

# OSIV setting
  jpa:
    open-in-view: false

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    doc-expansion: list
    operations-sorter: alpha
  version: v2.5.6

# aws settings
# S3 bucket region
cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      access-key: ${aws.access-key}
      secret-key: ${aws.secret-key}

google:
  application:
    credentials: ${google.application.credentials}